function h_ax2 = helper_copy_axes(h_ax)
%% HELPER_COPY_AXES is a helper that create an axes h_ax2 with
% some properties, e.g., YDir/XDir.
% It is used to create new axes in CANVAS figure.

% INPUT:
% h_ax: input axes

% OUTPUT:
% h_ax2: the axes copy

h_ax2 = axes( 'Parent', get(h_ax,'Parent'), ...
              'Unit', get(h_ax,'Unit'), ...
              'Position', get(h_ax,'Position'), ...
              'Color', get(h_ax,'Color'), ...
              'XDir', get(h_ax,'XDir'), ...
              'YDir', get(h_ax,'YDir'), ...
              'ZDir', get(h_ax,'ZDir'), ...
              'XLim', get(h_ax,'XLim'), ...
              'YLim', get(h_ax,'YLim'), ...
              'ZLim', get(h_ax,'ZLim'), ...
              'XTick', get(h_ax,'XTick'), ...
              'YTick', get(h_ax,'YTick'), ...
              'ZTick', get(h_ax,'ZTick'), ...
              'XLimMode',get(h_ax,'XLimMode'), ...
              'YLimMode',get(h_ax,'YLimMode'), ...
              'ZLimMode',get(h_ax,'ZLimMode'), ...
              'ALimMode',get(h_ax,'ALimMode'), ...
              'CLimMode',get(h_ax,'CLimMode'), ...
              'TickDirMode', get(h_ax,'TickDirMode'), ...
              'userdata',[]);

end