function init_canvas_gui
%% INIT_GUI initializes main figures: the toolbar and the main
%% canvas.

%% GLOBAL PARAM LIST
global IMG_INFO;
global CANVAS_INFO;
global TOOLBAR_INFO;

toolbar_pos = get(TOOLBAR_INFO.tb_handle,'Position');

% notes:
% for matlab R2014a, in linux, when the zbuffer/painter renderer is ...
% used, the alphadata for axes is not avialable; however, when the
% opengl is used, while an image is zoomed in, there is a bug,
% SOMETIMES!

%% CANVAS INIT
% IMPORTANT
% the renderer has to be zbuffer, because I will use alpha value
% here and opengl has bugs while I zoom in
h_cs = figure( ...
    'Name', ['Canvas:' num2str(CANVAS_INFO.curr_frame)], ...
    'NumberTitle', 'off', ...
    'Visible','off', ...
    'Position',[toolbar_pos(1)+toolbar_pos(3)+30 ...
                toolbar_pos(2) ...
                CANVAS_INFO.width ...
                CANVAS_INFO.height], ...
    'Units', 'pixels', ...
    'Menubar','none', ...
    'Renderer','painter', ... 
    'Resize','off');
set(h_cs, ...
    'WindowButtonDownFcn', '', ...
    'WindowButtonMotionFcn', '', ...
    'WindowButtonUpfcn', '', ...
    'WindowScrollWheelFcn',@scrollwheel_callback, ...
    'WindowKeyPressFcn', @canvas_keyboard_callback);

%% IMAGE DISPLAY INIT
h_axes = axes( ...
    'Parent', h_cs, ...
    'Units', 'normalized', ...
    'Position', [0 0 1 1], ...
    'Color', 'none', ...
    'TickDirMode','manual', ...
    'userdata', []);
set(h_axes, 'xtick', [], 'ytick', []); 
CANVAS_INFO.h_img = imshow(IMG_INFO.img(:,:,1), [], ...
                           'Parent', h_axes, ...
                           'Border', 'tight');
set(h_axes, 'XLimMode','manual',...
            'YLimMode','manual',...
            'ZLimMode','manual',...
            'CLimMode','manual',...
            'ALimMode','manual')
CANVAS_INFO.h_axes = h_axes;
axis(h_axes, 'manual');

%% Display the main window
% movegui(h_cs, 'southwest');
set(h_cs, 'Visible', 'on');
CANVAS_INFO.cs_handle = h_cs;
CANVAS_INFO.is_init = 1;

%% EXTENTION BEGIN
h_extra_axes = []; % used to display overlay
% test
% this cause opengl to fail .....
% h_extra_axes(1) = helper_copy_axes(h_axes);
% set(h_extra_axes(1),'Color','none');
% linkaxes([h_axes h_extra_axes]);
% h_l1 = line('Parent', h_extra_axes(1), ...
%             'XData', rand(10,1)*IMG_INFO.width, ...
%             'YData', rand(10,1)*IMG_INFO.height, ...
%             'Color', 'r', ...
%             'LineStyle', '-', ...
%             'Marker', 'o', ...
%             'MarkerSize',30, ...
%             'LineWidth', 20);
CANVAS_INFO.h_extra_axes = h_extra_axes;
%% EXTENTION END

end