function init_toolbar_gui
%% INIT_GUI initializes main figures: the toolbar and the main
%% canvas.

%% GLOBAL VARIABLES

%% GLOBAL PARAM LIST
global TOOLBAR_INFO;

%% TOOLBAR INIT
h_tb = figure( ...
    'Name', 'Toolbar', ...
    'NumberTitle', 'off', ...
    'Visible','off', ...
    'Position',[30 30 TOOLBAR_INFO.width TOOLBAR_INFO.height], ...
    'Units', 'pixels', ...
    'Menubar','none', ...
    'Resize','off');
set(h_tb, ...
    'windowbuttondownfcn', '', ...
    'windowbuttonmotionfcn', '', ...
    'windowbuttonupfcn', '');

for ii = 1:TOOLBAR_INFO.num_pbutt
    str = TOOLBAR_INFO.pbutt_names{ii};
    if numel(str)==0
        str=num2str(ii);
    end
    TOOLBAR_INFO.pbutts{ii} = uicontrol( ...
        'Parent', h_tb, ...
        'Style', 'pushbutton', ...
        'String', '', ...
        'TooltipString', str, ...
        'Position', [TOOLBAR_INFO.pbutt_x(ii), ...
                     TOOLBAR_INFO.pbutt_y(ii), ...
                     TOOLBAR_INFO.butt_size, ... 
                     TOOLBAR_INFO.butt_size], ...
        'CData', TOOLBAR_INFO.cdata{ii}, ...
        'Enable', 'on', ...
        'Callback', TOOLBAR_INFO.pbutt_callback{ii});
    setappdata(TOOLBAR_INFO.pbutts{ii},'appdata','');
    setappdata(TOOLBAR_INFO.pbutts{ii},'is_on',0);
end

% Display the main window
% movegui(h_tb, 'southwest');
set(h_tb, 'Visible', 'on');
TOOLBAR_INFO.tb_handle = h_tb;
TOOLBAR_INFO.is_init = 1;

end