function [x,fval,exitflag,output] = solve_intlinprog(c)
%% SOLVE_INTLINPROG solves the binary integer linear programming
% problem formulated by the cost matrix c.
% 
% This program mimicks the matchpairs function in R2019a
%
% Input:
% c: the cost matrix generated by the construct_cost.m function
% 
% Output:
% x: the solution

    [M,N] = size(c);
    if M~=N
        error('input must be a square matrix');
        return;
    end

    f = c(:); % vector collecting
    intvars = 1:length(f);
    lb = zeros(size(f));
    ub = lb + 1;
    beq = ones(2*N,1);
    Aeq = [kron(eye(N),ones(1,N));...
           kron(ones(1,N),eye(N))];

    % Solve the model
    opts = optimoptions(@linprog,'Display','off');
    [x,fval,exitflag,output] = linprog(f,[],[],Aeq,beq,lb,ub,opts);
end
