function mode_roia(obj)
    mode_reset(obj);
    obj.cur_mode = 'roia';
    set(obj.h_fig, ...
        'WindowButtonDownFcn', @obj.wbdcb, ...
        'WindowButtonMotionFcn', '', ...
        'WindowButtonUpfcn', '');
    set(obj.h_fig,'Pointer','custom',...
                  'PointerShapeCData',obj.custom_pointer,...
                  'PointerShapeHotSpot',[9 9]);
end
