function wbdcb(obj,src,evt)
    cur_point = get(obj.h_axes,'CurrentPoint');
    x = cur_point(1,1);
    y = cur_point(1,2);
    % point mode
    if strcmp(obj.cur_mode,'roip')
        [d,ind] = calc_closest_point(obj,x,y);
        if ind>0 && d<obj.PICK_R % pick existing point
            obj.active_ind = ind;
            set(obj.h_fig,'WindowButtonMotionFcn',...
                          {@obj.wbmcb,'move'},...
                          'WindowButtonUpFcn',...
                          {@obj.wbucb,'move'});
        else % add new point
            tmppoint = line('XData',x,...
                            'YData',y,...
                            'Marker',obj.PM,...
                            'Color',obj.PC,...
                            'MarkerSize',obj.PS,...
                            'MarkerFaceColor',obj.PC);
            set(obj.h_fig,'WindowButtonMotionFcn',...
                          {@obj.wbmcb,'add',tmppoint},...
                          'WindowButtonUpFcn',...
                          {@obj.wbucb,'add',tmppoint});
        end
    elseif strcmp(obj.cur_mode,'roia')
        [d,ind,arrowend] = calc_closest_arrow(obj,x,y);
        if ind>0 && d<obj.PICK_R % pick existing arrow
            obj.active_ind = ind;
            set(obj.h_fig,'WindowButtonMotionFcn',...
                          {@obj.wbmcb,'move',arrowend},...
                          'WindowButtonUpFcn',...
                          {@obj.wbucb,'move',arrowend});
        else % add new arrow
            tmparrow = arrow('Start',[x y],...
                             'Stop',[x y],...
                             'Color',obj.AC,...
                             'Width',obj.ALW,...
                             'Length',obj.AHL);
            set(obj.h_fig,'WindowButtonMotionFcn',...
                          {@obj.wbmcb,'add',tmparrow},...
                          'WindowButtonUpFcn',...
                          {@obj.wbucb,'add',tmparrow});
        end
        % rect mode
    elseif strcmp(obj.cur_mode,'roir')
        ind = calc_bounding_rect(obj,x,y);
        % rect move mode
        if ind>0
            obj.active_ind = ind;
            rectx0 = get(obj.lineroi.r{ind},'XData');
            recty0 = get(obj.lineroi.r{ind},'YData');
            set(obj.h_fig,'WindowButtonMotionFcn',...
                          {@obj.wbmcb,'move',x,y,rectx0,recty0},...
                          'WindowButtonUpFcn',...
                          {@obj.wbucb,'move'});
            % rect add mode
        else
            tmprect = line('XData',repmat(x,1,5),...
                           'YData',repmat(y,1,5),...
                           'Marker',obj.RM,...
                           'Color',obj.RC,...
                           'MarkerSize',obj.RS);
            set(obj.h_fig,'WindowButtonMotionFcn',...
                          {@obj.wbmcb,'add',x,y,tmprect},...
                          'WindowButtonUpFcn',...
                          {@obj.wbucb,'add',tmprect});
        end
    end
end
